/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ebsoniomsquare.view;

import java.util.ArrayList;
import ebsoniomsquare.MessageParamClass;
import ebsoniomsquare.model.CheckoutModel;
import ebsoniomsquare.model.ProductModel;
import ebsoniomsquare.services.CheckoutServices;
import ebsoniomsquare.services.ProductServices;
import ebsoniomsquare.servicesImpl.CheckoutServicesImpl;
import ebsoniomsquare.servicesImpl.ProductServicesImpl;
import java.util.Date;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bishal Shrestha
 */
public class CheckoutManagementMain extends javax.swing.JFrame {
    DefaultTableModel viewDefaultTableModel;
    /**
     * Creates new form SalesManagementMain
     */
    public CheckoutManagementMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        billNo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        customerID = new javax.swing.JTextField();
        newCustomer = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        checkOut = new javax.swing.JScrollPane();
        checkOutTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        quantity = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        totalField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        discountField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        grandTotalField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        receivedField = new javax.swing.JTextField();
        changeButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        returnField = new javax.swing.JTextField();
        checkOutbutton = new javax.swing.JButton();
        pdfGenerator = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        printReceiptLbl = new javax.swing.JTextArea();
        cancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bill No:");

        jLabel2.setText("Customer ID");

        customerID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerIDActionPerformed(evt);
            }
        });

        newCustomer.setText("New Customer");
        newCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCustomerActionPerformed(evt);
            }
        });

        jLabel3.setText("Ebsoniom Square Billing System");

        checkOutTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Quantity", "Price"
            }
        ));
        checkOutTable.setColumnSelectionAllowed(true);
        checkOut.setViewportView(checkOutTable);
        checkOutTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jLabel4.setText("Product ID: ");

        jLabel5.setText("Quantity: ");

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pid))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(quantity))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel7.setText("Total Amount: ");

        totalField.setEditable(false);

        jLabel6.setText("Discount Applicable Amount: ");

        discountField.setEditable(false);

        jLabel8.setText("Grand Total:");

        grandTotalField.setEditable(false);

        jLabel9.setText("Received:");

        changeButton.setText("Calculate Change");
        changeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeButtonActionPerformed(evt);
            }
        });

        jLabel10.setText("Return Amount: ");

        returnField.setEditable(false);

        checkOutbutton.setBackground(new java.awt.Color(204, 204, 204));
        checkOutbutton.setForeground(new java.awt.Color(51, 204, 0));
        checkOutbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ebsoniomsquare/icons/checkout.png"))); // NOI18N
        checkOutbutton.setText("Proceed Checkout");
        checkOutbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutbuttonActionPerformed(evt);
            }
        });

        pdfGenerator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ebsoniomsquare/icons/pdf-generator.png"))); // NOI18N
        pdfGenerator.setText("PDFGenerator");
        pdfGenerator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdfGeneratorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(discountField))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(jLabel8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(grandTotalField)
                            .addComponent(receivedField)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totalField))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(pdfGenerator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(checkOutbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(returnField, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 274, Short.MAX_VALUE)
                                        .addComponent(changeButton)))))
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(discountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(grandTotalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(receivedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changeButton)
                    .addComponent(jLabel10)
                    .addComponent(returnField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkOutbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(pdfGenerator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        printReceiptLbl.setColumns(20);
        printReceiptLbl.setRows(5);
        jScrollPane1.setViewportView(printReceiptLbl);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(checkOut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(38, 38, 38)
                                .addComponent(billNo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(customerID, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(newCustomer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cancelBtn)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(billNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(customerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newCustomer)
                    .addComponent(cancelBtn))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkOut, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 //Task Performed when New Customer Button is Clicked to open registration form
    private void newCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCustomerActionPerformed
        CustomerRegistrationMain frame = new CustomerRegistrationMain();
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(ManagementMain.DISPOSE_ON_CLOSE);
        frame.setVisible(true);
        frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_newCustomerActionPerformed
 //Task Performed when Add Button is Clicked
    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        CheckoutServices checkoutService = new CheckoutServicesImpl();
        CheckoutModel checkOut = new CheckoutModel();
        if(customerID.getText()!=""){
        checkOut.setCustomerID(customerID.getText());
        }else{
            checkOut.setCustomerID("GUEST");
        }
        checkOut.setBillingNo(billNo.getText());
        checkOut.setPid(pid.getText());
        checkOut.setQuantity(quantity.getText());
        checkoutService.addToTable(checkOut);
        getDataInTable(checkOut);
        pid.setText("");
        quantity.setText("");
    }//GEN-LAST:event_addButtonActionPerformed

    private void customerIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerIDActionPerformed
 //Task Performed when Delete Button is Clicked
    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
         if(checkOutTable.getSelectedRow()<0) {
                        JOptionPane.showMessageDialog(null, "Please select any product");
			return;
                    }
		int row=checkOutTable.getSelectedRow();
                String pid = (String) checkOutTable.getModel().getValueAt(row, 0);
                String bill = billNo.getText();
                CheckoutModel checkOut = new CheckoutModel();
                checkOut.setBillingNo(bill);
                checkOut.setPid(pid);
                CheckoutServices checkoutServices = new CheckoutServicesImpl();
                checkoutServices.deleteFromTable(checkOut);
                deleteFromTable(row);
    }//GEN-LAST:event_deleteButtonActionPerformed
 //Task Performed when CheckOut Button is Clicked
    private void checkOutbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutbuttonActionPerformed
        CheckoutModel checkoutModel = new CheckoutModel();
        checkoutModel.setBillingNo(billNo.getText());
        Date date = new Date();
        String currentDate = "";
        currentDate = String.valueOf(date);
        checkoutModel.setCurrentDate(currentDate);
        checkoutModel.setCustomerID(customerID.getText());
        checkoutModel.setDiscount(discountField.getText());
        checkoutModel.setGrandTot(grandTotalField.getText());
        checkoutModel.setTotalAmount(totalField.getText());
        checkoutModel.setReceivedAmount(receivedField.getText());
        checkoutModel.setReturnAmount(returnField.getText());
        CheckoutServices checkoutServices = new CheckoutServicesImpl();
        if(!(checkoutModel.getBillingNo()==""||checkoutModel.getGrandTot()==""||checkoutModel.getReceivedAmount()==""||checkoutModel.getReturnAmount()==""||checkoutModel.getBillingNo()=="")){
            MessageParamClass message = new MessageParamClass("Sure to Checkout?", "EbsoniomSquare Message"); 
            int returnOptionValue = message.showConfirmDialog();
            if(returnOptionValue==0){//0 is yes
                DefaultTableModel getModel = (DefaultTableModel)checkOutTable.getModel();
                int rowofTable = getModel.getRowCount();
                for(int countRow =0; countRow<rowofTable; countRow++){
                    String pid1 = (String)getModel.getValueAt(countRow, 0);
                    String quantity1 = (String)getModel.getValueAt(countRow, 2);
                    checkoutModel.setPid(pid1);
                    checkoutModel.setQuantity(quantity1);
                    if(checkoutServices.checkoutAll(checkoutModel)){
                        JOptionPane.showMessageDialog(null, "CheckedOut SuccessFully");
                        getModel.setRowCount(0);
                        generateReceipt(); 
                    }
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, "Some Field is still null!!");
        }
        
    }//GEN-LAST:event_checkOutbuttonActionPerformed
 //Task Performed when Change Button is Clicked to calculat the change amount
    private void changeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeButtonActionPerformed
        double received = Double.valueOf(receivedField.getText());
        double grandtotal = Double.valueOf(grandTotalField.getText());
        double ret = received - grandtotal;
        returnField.setText(String.valueOf(ret));
    }//GEN-LAST:event_changeButtonActionPerformed
 
    private void searchFilter(String query){
   }
    //generate receipt after checkout
    void generateReceipt(){
      Date obj= new Date();
      String date = obj.toString();
      float totalAmount= Float.parseFloat(totalField.getText());
      float discountAmount= Float.parseFloat(discountField.getText());
      float grandtotalAmount= Float.parseFloat(grandTotalField.getText());
      float returnAmount= Float.parseFloat(returnField.getText());
      float receivedAmount= Float.parseFloat(receivedField.getText());
      printReceiptLbl.setText("****************************\n");       
      printReceiptLbl.setText(printReceiptLbl.getText()+"***EbsoniomSquare SuperMarket Management System****\n");
      printReceiptLbl.setText(printReceiptLbl.getText()+"*** Branch Location: USQ Toowoomba ***\n");
      printReceiptLbl.setText(printReceiptLbl.getText()+"**Transaction Receipt**\n");
      printReceiptLbl.setText(printReceiptLbl.getText()+"**************************************\n");
      printReceiptLbl.setText(printReceiptLbl.getText()+"User: Bishal Shrestha\n");
      printReceiptLbl.setText(printReceiptLbl.getText()+"Counter No: 001\n");
      printReceiptLbl.setText(printReceiptLbl.getText()+"\n"+date+"\n");
      printReceiptLbl.setText(printReceiptLbl.getText()+"Customer ID:"+customerID.getText()+"\n");
      printReceiptLbl.setText(printReceiptLbl.getText()+"Bill/ Receipt ID:"+billNo.getText()+"\n");
      printReceiptLbl.setText(printReceiptLbl.getText()+"**************************************\n");
      printReceiptLbl.setText(printReceiptLbl.getText()+"\n"); 
      printReceiptLbl.setText(printReceiptLbl.getText()+"Total Transaction Amount($):"+totalAmount+"\n");
      printReceiptLbl.setText(printReceiptLbl.getText()+"Applicable Discount Amount($): "+discountAmount+"\n"); 
      printReceiptLbl.setText(printReceiptLbl.getText()+"Grand Total Amount($): "+grandtotalAmount+"\n");
      printReceiptLbl.setText(printReceiptLbl.getText()+"Received Amount($): "+receivedAmount+"\n");
      printReceiptLbl.setText(printReceiptLbl.getText()+"Return Amount($): "+returnAmount+"\n");
      printReceiptLbl.setText(printReceiptLbl.getText()+"***EbsoniomSquare SuperMarket Management System****\n");
      printReceiptLbl.setText(printReceiptLbl.getText()+"*** ThankYou for Shopping with us ***\n");
      printReceiptLbl.setText(printReceiptLbl.getText()+"**GoodDay! See You Again Soon**\n");
      printReceiptLbl.setText(printReceiptLbl.getText()+"**************************************\n");        
      MessageParamClass message = new MessageParamClass("Print Transaction Receipt?", "EbsoniomSquare Message"); 
            int returnOptionValue = message.showConfirmDialog();
            if(returnOptionValue==0){//0 is yes
                try{
                     printReceiptLbl.print();
                    // checkOutTable.getModel().getValueAt(0, 1);
                   }catch(Exception e){  
                       JOptionPane.showMessageDialog(null, "Cannot Print Receipt");
                    }
            } 
            //setting the text fields to empty
                        billNo.setText("");
                        customerID.setText("");
                        pid.setText("");
                        quantity.setText("");
                        totalField.setText("");
                        discountField.setText("");
                        grandTotalField.setText("");
                        receivedField.setText("");
                        returnField.setText("");
}
    private void pdfGeneratorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdfGeneratorActionPerformed
      
    }//GEN-LAST:event_pdfGeneratorActionPerformed
 //Task Performed when Cancel Button is Clicked
    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        MessageParamClass message = new MessageParamClass("Cancel CheckOut Process", "EbsoniomSquare Message"); 
            int returnOptionValue = message.showConfirmDialog();
        if(returnOptionValue==0){ //value of yes = 0
        setVisible(false);
        CheckoutManagementPanelMain frame = new CheckoutManagementPanelMain();
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(ManagementMain.DISPOSE_ON_CLOSE);
        frame.setVisible(true);
        }
    }//GEN-LAST:event_cancelBtnActionPerformed
/*Delete from table*/
    private void deleteFromTable(int row){
        DefaultTableModel model=(DefaultTableModel)checkOutTable.getModel();
        model.removeRow(row);
        setTotalAmount(model);
    }
    /*Set Total Amount*/
   private void setTotalAmount(DefaultTableModel model){
       int row = model.getRowCount();
       System.out.println(row);
        if(row==0){
            totalField.setText("0");
            discountField.setText("0");
            grandTotalField.setText("0");
        }else{
            double sum = 0;
       for(int i = 0;i < row; i++){
             double total=(double) checkOutTable.getModel().getValueAt(i, 3);//price;
               System.out.println(total+"  "+ row);
             sum=sum+total;
        }
        totalField.setText(String.valueOf(sum));
            discountField.setText(String.valueOf(0.1*sum));
            grandTotalField.setText(String.valueOf(sum-0.1*sum));
        }
    }
    /*get Data in the table;*/
    private void getDataInTable(CheckoutModel checkOut){
        ProductServices productService = new ProductServicesImpl();
        ProductModel productModel = productService.getById(checkOut.getPid());
        DefaultTableModel model=(DefaultTableModel)checkOutTable.getModel();
        //model.setRowCount(0);
        	model.addRow(new Object[] {productModel.getPid(),productModel.getProductName()
                        ,checkOut.getQuantity(),
                        (Double.parseDouble(checkOut.getQuantity()))*(Double.parseDouble(productModel.getPrice())),
                        });
	        setTotalAmount(model); 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckoutManagementMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckoutManagementMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckoutManagementMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckoutManagementMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckoutManagementMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextField billNo;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton changeButton;
    private javax.swing.JScrollPane checkOut;
    private javax.swing.JTable checkOutTable;
    private javax.swing.JButton checkOutbutton;
    private javax.swing.JTextField customerID;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField discountField;
    private javax.swing.JTextField grandTotalField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton newCustomer;
    private javax.swing.JButton pdfGenerator;
    private javax.swing.JTextField pid;
    private javax.swing.JTextArea printReceiptLbl;
    private javax.swing.JTextField quantity;
    private javax.swing.JTextField receivedField;
    private javax.swing.JTextField returnField;
    private javax.swing.JTextField totalField;
    // End of variables declaration//GEN-END:variables
}
