/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ebsoniomsquare.view;

import ebsoniomsquare.DBConnClass;
import ebsoniomsquare.MessageParamClass;
import ebsoniomsquare.model.EmployeeViewDetailsClass;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Bishal Shrestha
 */
//Form for View Employee Details
public class EmployeeViewDetailsMain extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeViewDetailsMain
     */
    public EmployeeViewDetailsMain() {
        initComponents();
        EmployeeViewDetailsClass();
    }
    
    public ArrayList<EmployeeViewDetailsClass> userList(){
    ArrayList<EmployeeViewDetailsClass> employeeList = new ArrayList<>(); //Create Object named Arraylist
    //Select Data from the Database
    try{
            //Query for selecting data from the database
            String sqlQuery = "SELECT * FROM MANAGEMENT "; 
            //Invoking DBConnClass to View the data in the database
            ResultSet rs = DBConnClass.getData(sqlQuery); 
            //Create Object for EmployeeDetails
            EmployeeViewDetailsClass employeeViewDetails;
             while(rs.next()){ 
                 employeeViewDetails = new EmployeeViewDetailsClass(rs.getInt("SNO"), rs.getString("BRANCH"), 
                         rs.getString("DEPARTMENT"), rs.getString("DESIGNATION"), rs.getString("TITLE"), 
                         rs.getString("NAME"), rs.getString("GENDER"), rs.getString("MARITIAL"), 
                         rs.getString("NATIONALITY"), rs.getString("DOB"), rs.getString("EDUCATION"), 
                         rs.getString("FATHER"), rs.getString("MOTHER"), rs.getString("PADDRESS"), 
                         rs.getString("TADDRESS"), rs.getString("CONTACT"), rs.getString("EMAIL"), 
                         rs.getString("USERNAME"));
             employeeList.add(employeeViewDetails);
             }
    }catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
            } 
    return employeeList; //Return Employee Details
    }
    
    public void EmployeeViewDetailsClass(){
        ArrayList<EmployeeViewDetailsClass> list = userList();
        DefaultTableModel model = (DefaultTableModel)viewEmployeeDetailsTbl.getModel();//typecast with default table model
        Object[] row = new Object[19]; 
        for(int i=0; i<list.size();i++){
            row[0] = list.get(i).getSno();
            row[1] = list.get(i).getBranch();
            row[2] = list.get(i).getTitle();
            row[3] = list.get(i).getName();
            row[4] = list.get(i).getGender(); 
            row[5] = list.get(i).getMaritial();
            row[6] = list.get(i).getNationality();
            row[7] = list.get(i).getDateOfBirth();
            row[8] = list.get(i).getEducation();
            row[9] = list.get(i).getFather(); 
            row[10] = list.get(i).getMother();
            row[11] = list.get(i).getPermanentAddress();
            row[12] = list.get(i).getTemporaryAddress();
            row[13] = list.get(i).getContact();
            row[14] = list.get(i).getEmail(); 
            row[15] = list.get(i).getUserName();
            row[16] = list.get(i).getDepartment();
            row[17] = list.get(i).getDesignation();
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewEmployeeDetailsTbl = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        branchNameLbl = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        titleMrOp = new javax.swing.JRadioButton();
        titleMsOp = new javax.swing.JRadioButton();
        titleMrsOp = new javax.swing.JRadioButton();
        titleOtherOp = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nameFld = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        genderMaleOp = new javax.swing.JRadioButton();
        genderFemaleOp = new javax.swing.JRadioButton();
        genderOtherOp = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        maritialSingleOp = new javax.swing.JRadioButton();
        maritialMarriedOp = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        nationalityFld = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        dobFld = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        educationFld = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        fatherNameFld = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        motherNameLbl = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        permanentAddressFld = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        temporaryAddressFld = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        mobileNumberLbl = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        emailIdFld = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        departmentFld = new javax.swing.JTextField();
        designationFld = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        usernameFld = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        viewEmployeeDetailsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.No.", "Branch", "Department", "Designation", "Salutation", "Full Name", "Gender", "Maritial Status", "Nationality", "D.O.B", "Education", "Father Name", "Mother Name", "Permanent Address", "Temporary Address", "Contact", "Email ID", "Username"
            }
        ));
        viewEmployeeDetailsTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewEmployeeDetailsTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(viewEmployeeDetailsTbl);
        if (viewEmployeeDetailsTbl.getColumnModel().getColumnCount() > 0) {
            viewEmployeeDetailsTbl.getColumnModel().getColumn(0).setMinWidth(0);
            viewEmployeeDetailsTbl.getColumnModel().getColumn(0).setPreferredWidth(0);
            viewEmployeeDetailsTbl.getColumnModel().getColumn(0).setMaxWidth(0);
            viewEmployeeDetailsTbl.getColumnModel().getColumn(7).setMinWidth(0);
            viewEmployeeDetailsTbl.getColumnModel().getColumn(7).setPreferredWidth(0);
            viewEmployeeDetailsTbl.getColumnModel().getColumn(7).setMaxWidth(0);
            viewEmployeeDetailsTbl.getColumnModel().getColumn(9).setMinWidth(0);
            viewEmployeeDetailsTbl.getColumnModel().getColumn(9).setPreferredWidth(0);
            viewEmployeeDetailsTbl.getColumnModel().getColumn(9).setMaxWidth(0);
            viewEmployeeDetailsTbl.getColumnModel().getColumn(10).setMinWidth(0);
            viewEmployeeDetailsTbl.getColumnModel().getColumn(10).setPreferredWidth(0);
            viewEmployeeDetailsTbl.getColumnModel().getColumn(10).setMaxWidth(0);
            viewEmployeeDetailsTbl.getColumnModel().getColumn(11).setMinWidth(0);
            viewEmployeeDetailsTbl.getColumnModel().getColumn(11).setPreferredWidth(0);
            viewEmployeeDetailsTbl.getColumnModel().getColumn(11).setMaxWidth(0);
            viewEmployeeDetailsTbl.getColumnModel().getColumn(12).setMinWidth(0);
            viewEmployeeDetailsTbl.getColumnModel().getColumn(12).setPreferredWidth(0);
            viewEmployeeDetailsTbl.getColumnModel().getColumn(12).setMaxWidth(0);
            viewEmployeeDetailsTbl.getColumnModel().getColumn(13).setMinWidth(0);
            viewEmployeeDetailsTbl.getColumnModel().getColumn(13).setPreferredWidth(0);
            viewEmployeeDetailsTbl.getColumnModel().getColumn(13).setMaxWidth(0);
            viewEmployeeDetailsTbl.getColumnModel().getColumn(14).setMinWidth(0);
            viewEmployeeDetailsTbl.getColumnModel().getColumn(14).setPreferredWidth(0);
            viewEmployeeDetailsTbl.getColumnModel().getColumn(14).setMaxWidth(0);
            viewEmployeeDetailsTbl.getColumnModel().getColumn(16).setMinWidth(0);
            viewEmployeeDetailsTbl.getColumnModel().getColumn(16).setPreferredWidth(0);
            viewEmployeeDetailsTbl.getColumnModel().getColumn(16).setMaxWidth(0);
            viewEmployeeDetailsTbl.getColumnModel().getColumn(17).setMinWidth(0);
            viewEmployeeDetailsTbl.getColumnModel().getColumn(17).setPreferredWidth(0);
            viewEmployeeDetailsTbl.getColumnModel().getColumn(17).setMaxWidth(0);
        }

        jLabel3.setText("Branch:");

        branchNameLbl.setEditable(false);

        jLabel5.setText("Title:");

        titleMrOp.setText("Mr.");
        titleMrOp.setEnabled(false);

        titleMsOp.setText("Ms.");
        titleMsOp.setEnabled(false);

        titleMrsOp.setText("Mrs.");
        titleMrsOp.setEnabled(false);

        titleOtherOp.setText("Other");
        titleOtherOp.setEnabled(false);

        jLabel1.setText("Department: ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(branchNameLbl))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(titleMrOp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(titleMsOp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(titleMrsOp)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(titleOtherOp))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(branchNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(titleMrOp)
                    .addComponent(titleMsOp)
                    .addComponent(titleMrsOp)
                    .addComponent(titleOtherOp))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel6.setText("Name:");

        nameFld.setEditable(false);

        jLabel7.setText("Gender:");

        genderMaleOp.setText("Male");
        genderMaleOp.setEnabled(false);

        genderFemaleOp.setText("Female");
        genderFemaleOp.setEnabled(false);

        genderOtherOp.setText("Other");
        genderOtherOp.setEnabled(false);

        jLabel9.setText("Maritial Status: ");

        maritialSingleOp.setText("Single");
        maritialSingleOp.setEnabled(false);
        maritialSingleOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maritialSingleOpActionPerformed(evt);
            }
        });

        maritialMarriedOp.setText("Married");
        maritialMarriedOp.setEnabled(false);

        jLabel10.setText("Nationality:");

        nationalityFld.setEditable(false);

        jLabel11.setText("Date of Birth:");

        dobFld.setEnabled(false);

        jLabel14.setText("Education:");

        educationFld.setEditable(false);

        jLabel15.setText("Father's Name:");

        fatherNameFld.setEditable(false);

        jLabel16.setText("Mother's Name:");

        motherNameLbl.setEditable(false);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setText("Address");

        jLabel20.setText("Permanent Address:");

        permanentAddressFld.setEditable(false);

        jLabel21.setText("Temporary Address:");

        temporaryAddressFld.setEditable(false);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setText("Contact Information");

        jLabel23.setText("Mobile Number:");

        mobileNumberLbl.setEditable(false);

        jLabel24.setText("Email ID:");

        emailIdFld.setEditable(false);

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        departmentFld.setEditable(false);
        departmentFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentFldActionPerformed(evt);
            }
        });

        designationFld.setEditable(false);

        jLabel2.setText("Designation:");

        jLabel4.setText("Username: ");

        usernameFld.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fatherNameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel27)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(permanentAddressFld, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel24)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(emailIdFld))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(temporaryAddressFld))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(18, 18, 18)
                                        .addComponent(motherNameLbl))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(genderMaleOp)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(genderFemaleOp)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(genderOtherOp))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dobFld, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mobileNumberLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel25))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(departmentFld, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(designationFld, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(usernameFld, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(18, 18, 18)
                                        .addComponent(educationFld))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(maritialSingleOp)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(maritialMarriedOp)
                                        .addGap(38, 38, 38)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nationalityFld))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(nameFld))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(departmentFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(designationFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(usernameFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(genderMaleOp)
                        .addComponent(genderFemaleOp)
                        .addComponent(genderOtherOp))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(maritialSingleOp)
                        .addComponent(maritialMarriedOp)
                        .addComponent(jLabel10)
                        .addComponent(nationalityFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dobFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(educationFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(3, 3, 3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(fatherNameFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(motherNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(permanentAddressFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(temporaryAddressFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(mobileNumberLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(emailIdFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void maritialSingleOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maritialSingleOpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maritialSingleOpActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Objects to Show Cancel Employee View Details Message
        MessageParamClass message = new MessageParamClass("Sure to Cancel?", "Cancel?");
        int returnOptionValue = message.showConfirmDialog();

        if(returnOptionValue==0){  //value of yes = 0
            EmployeePanelMain frame = new EmployeePanelMain();
            frame.setLocationRelativeTo(null);
            frame.setDefaultCloseOperation(ManagementMain.DISPOSE_ON_CLOSE);
            frame.setVisible(true);
            setVisible(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void viewEmployeeDetailsTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewEmployeeDetailsTblMouseClicked
        //Display the selected fields in the Text Box
        int i = viewEmployeeDetailsTbl.getSelectedRow();
        TableModel model= viewEmployeeDetailsTbl.getModel();
        
        branchNameLbl.setText(model.getValueAt(i,1).toString());
        departmentFld.setText(model.getValueAt(i,2).toString());
        designationFld.setText(model.getValueAt(i,3).toString());
        String salutation = model.getValueAt(i,4).toString();
        if(salutation.equals("Mr")){
            titleMrOp.setSelected(true);
            titleMrsOp.setSelected(false);
            titleMsOp.setSelected(false);
            titleOtherOp.setSelected(false);
        }if(salutation.equals("Mrs")){
            titleMrOp.setSelected(false);
            titleMrsOp.setSelected(true);
            titleMsOp.setSelected(false);
            titleOtherOp.setSelected(false);
        }if(salutation.equals("Ms")){
            titleMrOp.setSelected(false);
            titleMrsOp.setSelected(false);
            titleMsOp.setSelected(true);
            titleOtherOp.setSelected(false);
        }if(salutation.equals("Other")){
            titleMrOp.setSelected(false);
            titleMrsOp.setSelected(false);
            titleMsOp.setSelected(false);
            titleOtherOp.setSelected(true);
        }
        nameFld.setText(model.getValueAt(i,5).toString());
        String gender = model.getValueAt(i,6).toString();
        if(gender.equals("Male")){
            genderMaleOp.setSelected(true);
            genderFemaleOp.setSelected(false);
            genderOtherOp.setSelected(false);
        }if(gender.equals("Female")){
            genderMaleOp.setSelected(false);
            genderFemaleOp.setSelected(true);
            genderOtherOp.setSelected(false);
        }if(gender.equals("other")){
            genderMaleOp.setSelected(false);
            genderFemaleOp.setSelected(false);
            genderOtherOp.setSelected(true);
        }
        String maritialStatus = model.getValueAt(i,7).toString();
        if(maritialStatus.equals("Single")){
            maritialSingleOp.setSelected(true);
            maritialMarriedOp.setSelected(false);
        }if(maritialStatus.equals("Married")){
            maritialSingleOp.setSelected(false);
            maritialMarriedOp.setSelected(true);
        } 
        nationalityFld.setText(model.getValueAt(i,8).toString());
        try{
           Date date= new SimpleDateFormat("yyyy-MM-dd").parse((String)model.getValueAt(i,9));
           dobFld.setDate(date);
        }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
            }
        educationFld.setText(model.getValueAt(i,10).toString());
        fatherNameFld.setText(model.getValueAt(i,11).toString());
        motherNameLbl.setText(model.getValueAt(i,12).toString());
        permanentAddressFld.setText(model.getValueAt(i,13).toString());
        temporaryAddressFld.setText(model.getValueAt(i,14).toString());
        mobileNumberLbl.setText(model.getValueAt(i,15).toString());
        emailIdFld.setText(model.getValueAt(i,16).toString());
        usernameFld.setText(model.getValueAt(i,17).toString());
        mobileNumberLbl.setText(model.getValueAt(i,18).toString());   
    }//GEN-LAST:event_viewEmployeeDetailsTblMouseClicked

    private void departmentFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departmentFldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeViewDetailsMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeViewDetailsMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeViewDetailsMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeViewDetailsMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeViewDetailsMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField branchNameLbl;
    private javax.swing.JTextField departmentFld;
    private javax.swing.JTextField designationFld;
    private com.toedter.calendar.JDateChooser dobFld;
    private javax.swing.JTextField educationFld;
    private javax.swing.JTextField emailIdFld;
    private javax.swing.JTextField fatherNameFld;
    private javax.swing.JRadioButton genderFemaleOp;
    private javax.swing.JRadioButton genderMaleOp;
    private javax.swing.JRadioButton genderOtherOp;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton maritialMarriedOp;
    private javax.swing.JRadioButton maritialSingleOp;
    private javax.swing.JTextField mobileNumberLbl;
    private javax.swing.JTextField motherNameLbl;
    private javax.swing.JTextField nameFld;
    private javax.swing.JTextField nationalityFld;
    private javax.swing.JTextField permanentAddressFld;
    private javax.swing.JTextField temporaryAddressFld;
    private javax.swing.JRadioButton titleMrOp;
    private javax.swing.JRadioButton titleMrsOp;
    private javax.swing.JRadioButton titleMsOp;
    private javax.swing.JRadioButton titleOtherOp;
    private javax.swing.JTextField usernameFld;
    private javax.swing.JTable viewEmployeeDetailsTbl;
    // End of variables declaration//GEN-END:variables
}
